# -*- coding: utf-8 -*-
"""AQI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRJqqgLhtsG4aLtzA-__r2guZh1Yzrj7
"""

pip install pandas numpy matplotlib seaborn scikit-learn streamlit joblib

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.read_csv("city_day.csv.zip")

print(df.head())

df = df[
[
'PM2.5',
'PM10',
'NO2',
'SO2',
'CO',
'O3',
'AQI'
]
]

#Handle Missing Values

df = df.fillna(df.mean(numeric_only=True))

print(df.isnull().sum())

#Define Features and Target

X = df[['PM2.5','PM10','NO2','SO2','CO','O3']]

y = df['AQI']

#Split Dataset

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X,
y,
test_size=0.20,
random_state=42
)

#Train Linear Regression Model

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

lr_pred = lr.predict(X_test)

#Train Decision Tree Model

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
random_state=42
)

dt.fit(X_train,y_train)

dt_pred = dt.predict(X_test)

#Train Random Forest Model

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
n_estimators=100,
random_state=42
)

rf.fit(X_train,y_train)

rf_pred = rf.predict(X_test)

#Evaluate Models

from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

print("Linear Regression")

print("R2 Score:",
r2_score(y_test,lr_pred))

print("MAE:",
mean_absolute_error(y_test,lr_pred))

print("--------------------------------")

print("Decision Tree")

print("R2 Score:",
r2_score(y_test,dt_pred))

print("MAE:",
mean_absolute_error(y_test,dt_pred))

print("--------------------------------")

print("Random Forest")

print("R2 Score:",
r2_score(y_test,rf_pred))

print("MAE:",
mean_absolute_error(y_test,rf_pred))

import joblib

joblib.dump(
rf,
"aqi_model.pkl"
)

print("Model Saved Successfully")